#platform :ios, '15.0'
platform :ios, '18.0'
use_frameworks!

target 'iosApp' do
  # Pods for ML Kit
  #pod 'GoogleMLKit/TextRecognitionChinese', '4.0.0'
  #pod 'GoogleMLKit/Translate', '4.0.0'
 
end
# post_install do |installer|
#      installer.generated_projects.each do |project|
#            project.targets.each do |target|
#                target.build_configurations.each do |config|
##                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
#                 end
#            end
#     end
#  end
#end
